### ISSUE TITLE
Link is down

### ISSUE THREAD

**Issue by PseudoSky** [cmu-student-government/shinymetal#96]
Not sure if it's down bc it's not a browser page or something, but - 
the link https://stugov.cmu.edu/bridgeapi in the description shows 

<img width="535" alt="screen shot 2016-02-06 at 1 45 48 pm" src="https://cloud.githubusercontent.com/assets/3356993/12868626/247ec524-ccd8-11e5-9f22-fa4c6456a32f.png">

**Comment by jkcorrea** [comment]
Thanks for the heads up :+1: site should be back up now!
